apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: desafio-backstageio
  title: Template do desafio Backstage.io
  description: Template para a criação de um novo repositório no Azure Devops.
spec:
  owner: Mariano-SI
  type: service
  parameters:
    - title: Fill in the basic information about the new project
      required:
        - projectName
        - serviceName
      properties:
        projectName:
          title: Name of project
          type: string
          description: Unique name of the project
          ui:autofocus: true
          ui:options:
            rows: 5
        serviceName:
          title: Name of service
          type: string
          description: Add a name to the new service
          ui:options:
            rows: 5
    - title: Fill the informations about the new repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com  
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: https://github.com/Mariano-SI/template-desafio-backstageio/tree/master/contents
        values:
          projectName: ${{ parameters.projectName }}
          serviceName: ${{parameters.serviceName}}

    - id: publish-azure
      name: Publish to Azure DevOps
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        repoUrl: ${{ parameters.repoUrl }}
        organization: ${{ parseRepoUrl(parameters.repoUrl).organization }}
        project: ${{ parseRepoUrl(parameters.repoUrl).project }}
        repo: ${{ parseRepoUrl(parameters.repoUrl).repo }}
        description: This is ${{ parameters.description }}
    
    - id: Register 
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-azure'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'